version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=123456
      - API_BASE_URL=https://maestro-api-dev.secil.biz
      - API_SECRET_TOKEN=YOUR_SECRET_TOKEN
      - NEXT_PUBLIC_API_URL=https://maestro-api-dev.secil.biz

